# Generated by Django 6.0.3 on 2026-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
    ]
